services:
  - type: web
    name: demon-slayer-bot
    runtime: python
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: MONGO_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
        
